# Generated by Django 2.0.5 on 2018-07-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
